<?php 
$title = "Terms & Conditions - The Admin Practice";
include "header.php";
?>
<link rel="stylesheet" type="text/css" href="./css/privacy-policy.css">
<div class="container">
    <h1 class="caps">TERMS & CONDITIONS</h1>
    <h2 class="caps">Introduction</h2>
    <p>Welcome to The Admin Practice: <a href="https://theadminpractice.co.uk">www.theadminpractice.co.uk</a>.</p>
    <p>‘You’ or ‘your’ refers to the user or viewer of our website. If you continue to browse and use this website you agree to comply with and be bound by the following terms and conditions, which together with our privacy policy govern our relationship with you in relation to this website and services made using it. If you disagree with any part of these terms and conditions, please do not continue to use our website.</p>
    <h2 class="caps">Terms of Website Use</h2>
    <p>The content of this website is for your general information and use only. It is subject to change without notice other than as set out below. Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials found or offered on this website for any particular purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.</p>
    <p>Your use of any information or materials on this website is entirely at your own risk, for which we shall not be liable. It shall be your own responsibility to ensure that any products or information available through this website meet your specific requirements. This website contains material which is owned by or licensed to us. This material includes, but is not limited to, the design, layout, look, appearance, and graphics. Reproduction of these is prohibited.</p>
    <p>All trademarks reproduced in this website, which are not the property of, or licensed to the operator, are acknowledged on the website. Unauthorised use of this website may give rise to a claim for damages and/or may be a criminal offence. From time to time, this website may also include links to other websites. These links are provided for your convenience to provide further information. They do not signify that we endorse the website(s). We have no responsibility for the content of the linked website(s).</p>
    <p>Whenever you make use of a feature that allows you to upload content to our site or any site (including social media pages) run by us, either for the purposes of an order or otherwise, such content must not contain any material which is defamatory, obscene, offensive, hateful, inflammatory, sexually explicit, violent, discriminatory, deceitful, infringing of the rights of or duties owed to any third party, illegal, threatening, abusive, harassing, capable of being used to impersonate any person or to misrepresent your identity or affiliation with any person, or advocate, promote or assist any of the above.</p>
    <p>You warrant that any such contribution does comply with those standards, and you will be liable to us and indemnify us for any breach of that warranty. This means you will be responsible for any loss or damage we suffer as a result of your breach of warranty. Any content you upload to our site will be considered non-confidential and non-proprietary. You retain all your ownership rights in your content, but you are required to grant us [and other users of our site] a limited licence to use, store and copy that content and to distribute and make it available to third parties.</p>
    <p>We also have the right to disclose your identity to any third party who is claiming that any content posted or uploaded by you to our site constitutes a violation of their intellectual property rights, or of their right to privacy.</p>
    <p>We have the right to remove any posting you make on our site if, in our opinion, your post does not comply with the content standards set out in our Acceptable Use Policy. You are solely responsible for securing and backing up your content.</p>
    <p>We do not guarantee that our site will be secure or free from bugs or viruses. You are responsible for configuring your information technology, computer programmes and platform to access our site. You should use your own virus protection software. When making any payment you must ensure that you are using a secure network. We cannot guarantee security of your payment data if you are using an unsecured network such as public WI-FI.</p>
    <p>You must not misuse our site by knowingly introducing viruses, trojans, worms, logic bombs or other material that is malicious or technologically harmful. You must not attempt to gain unauthorised access to our site, the server on which our site is stored, or any server, computer or database connected to our site. You must not attack our site via a denial-of-service attack or a distributed denial-of service attack. By breaching this provision, you would commit a criminal offence under the Computer Misuse Act 1990. We will report any such breach to the relevant law enforcement authorities, and we will co-operate with those authorities by disclosing your identity to them. In the event of such a breach, your right to use our site will cease immediately.</p>
    <p>Your use of this website and any dispute arising out of such use of the website is subject to the laws of England and Wales.</p>
    <h2 class="caps">General</h2>
    <p>Nobody else has any rights under this contract. This contract is between you and us.</p>
    <p>Each of the paragraphs of these terms operates separately. If any court or relevant authority decides that any of them are unlawful, the remaining paragraphs will remain in full force and effect.</p>
    <p>If we do not insist immediately that you do anything you are required to do under these terms, or if we delay in taking steps against you in respect of your breaking this contract, that will not mean that you do not have to do those things and it will not prevent us taking steps against you at a later date.</p>
    <p>We reserve the right to change these Terms and Conditions at any time.</p>
    <p>These terms are governed by the laws of England and Wales.</p>
</div>
<?php 
    include "footer.php";
?>